spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:mysql://${DATABASE_URL:localhost:3306/fakestore_db_demo}
spring.datasource.username=${DATABASE_USER:placeholder}
spring.datasource.password=${DATABASE_PASSWORD:placeholder}